export default {
  at: "2024-04-03T14:11:54.440Z",
  products: [
    {
      description: "velit exercitation elit dolore",
      name: "do",
      price: 747.74,
      tmpProperty: undefined,
      activePromoId: 60,
    },
    {
      description: "est nostrud nulla cillum",
      name: "officia",
      price: 1969.5,
      tmpProperty: undefined,
      activePromoId: 7,
    },
    {
      description: "laboris et eiusmod incididunt",
      name: "enim",
      price: 853.48,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "reprehenderit velit ad amet",
      name: "velit",
      price: 740.3,
      tmpProperty: undefined,
      activePromoId: 90,
    },
    {
      description: "ullamco id mollit Lorem",
      name: "magna",
      price: 1616.15,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "minim labore officia cupidatat",
      name: "eiusmod",
      price: 1913.6,
      tmpProperty: undefined,
      activePromoId: 65,
    },
    {
      description: "duis dolor anim laboris",
      name: "laboris",
      price: 632.81,
      tmpProperty: undefined,
      activePromoId: 89,
    },
    {
      description: "do labore laborum aliquip",
      name: "consequat",
      price: 910.38,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "qui proident non enim",
      name: "duis",
      price: 261.71,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "eu amet qui id",
      name: "sint",
      price: 1560.46,
      tmpProperty: undefined,
      activePromoId: 72,
    },
    {
      description: "ipsum cillum ad velit",
      name: "proident",
      price: 250.93,
      tmpProperty: undefined,
      activePromoId: 76,
    },
    {
      description: "mollit nulla proident deserunt",
      name: "consectetur",
      price: 1342.16,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "est sint irure dolor",
      name: "id",
      price: 759.05,
      tmpProperty: undefined,
      activePromoId: 16,
    },
    {
      description: "in ea nisi laborum",
      name: "ipsum",
      price: 602.97,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "veniam aliqua eu qui",
      name: "veniam",
      price: 1674.05,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "minim esse nostrud ex",
      name: "velit",
      price: 251.68,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "occaecat commodo commodo Lorem",
      name: "nostrud",
      price: 1844.9,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "fugiat incididunt sunt sit",
      name: "elit",
      price: 1179.98,
      tmpProperty: undefined,
      activePromoId: 67,
    },
    {
      description: "mollit Lorem mollit ut",
      name: "id",
      price: 1634.53,
      tmpProperty: undefined,
      activePromoId: 77,
    },
    {
      description: "aliquip laborum officia qui",
      name: "aliquip",
      price: 1768.34,
      tmpProperty: undefined,
      activePromoId: 5,
    },
    {
      description: "commodo cupidatat velit laboris",
      name: "cillum",
      price: 1674.03,
      tmpProperty: undefined,
      activePromoId: 33,
    },
    {
      description: "magna dolore aliquip irure",
      name: "incididunt",
      price: 1789.23,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "consectetur commodo ipsum sunt",
      name: "pariatur",
      price: 1873.34,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "occaecat tempor reprehenderit ad",
      name: "cillum",
      price: 1371.15,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "veniam incididunt eu mollit",
      name: "pariatur",
      price: 728.7,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "duis elit laboris consequat",
      name: "cupidatat",
      price: 1275.72,
      tmpProperty: undefined,
      activePromoId: 54,
    },
    {
      description: "culpa occaecat minim id",
      name: "ea",
      price: 1048.24,
      tmpProperty: undefined,
      activePromoId: 46,
    },
    {
      description: "duis officia qui et",
      name: "ea",
      price: 1107.29,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "velit minim cupidatat sint",
      name: "occaecat",
      price: 455.49,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "cupidatat ea voluptate eiusmod",
      name: "enim",
      price: 1079.13,
      tmpProperty: undefined,
      activePromoId: 96,
    },
    {
      description: "reprehenderit veniam ea aute",
      name: "ipsum",
      price: 442.53,
      tmpProperty: undefined,
      activePromoId: 34,
    },
    {
      description: "in non consectetur reprehenderit",
      name: "deserunt",
      price: 507.43,
      tmpProperty: undefined,
      activePromoId: 44,
    },
    {
      description: "ea cillum anim sunt",
      name: "eiusmod",
      price: 1839,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "labore sint dolore minim",
      name: "dolor",
      price: 975.22,
      tmpProperty: undefined,
      activePromoId: 13,
    },
    {
      description: "officia et labore ut",
      name: "velit",
      price: 940.92,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "Lorem nulla labore labore",
      name: "et",
      price: 1106.41,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "non id eiusmod eu",
      name: "pariatur",
      price: 813.93,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "duis sit ex irure",
      name: "amet",
      price: 640.14,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "aliquip ullamco excepteur commodo",
      name: "magna",
      price: 391.64,
      tmpProperty: undefined,
      activePromoId: 7,
    },
    {
      description: "cillum enim quis eiusmod",
      name: "aute",
      price: 1055.74,
      tmpProperty: undefined,
      activePromoId: 27,
    },
    {
      description: "aliqua eu duis cillum",
      name: "elit",
      price: 1924.07,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "qui ipsum anim anim",
      name: "id",
      price: 1055.43,
      tmpProperty: undefined,
      activePromoId: 17,
    },
    {
      description: "id sint amet sunt",
      name: "ex",
      price: 1665.72,
      tmpProperty: undefined,
      activePromoId: 59,
    },
    {
      description: "ex ut veniam Lorem",
      name: "sint",
      price: 1687.13,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "reprehenderit sint sit magna",
      name: "deserunt",
      price: 130.75,
      tmpProperty: undefined,
      activePromoId: 82,
    },
    {
      description: "ea et nulla ullamco",
      name: "dolore",
      price: 1779.89,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "nulla commodo mollit nisi",
      name: "dolor",
      price: 738.45,
      tmpProperty: undefined,
      activePromoId: 86,
    },
    {
      description: "est veniam incididunt eu",
      name: "dolore",
      price: 122.28,
      tmpProperty: undefined,
      activePromoId: 44,
    },
    {
      description: "esse nulla nulla sunt",
      name: "Lorem",
      price: 1276.4,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "id occaecat est esse",
      name: "esse",
      price: 196.23,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "aute cupidatat id dolor",
      name: "labore",
      price: 431.5,
      tmpProperty: undefined,
      activePromoId: 59,
    },
    {
      description: "est tempor voluptate ut",
      name: "do",
      price: 1171.08,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "nulla quis id enim",
      name: "cupidatat",
      price: 286.15,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "nostrud proident reprehenderit qui",
      name: "ut",
      price: 890.15,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "sint cupidatat quis consequat",
      name: "voluptate",
      price: 221.02,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ad id non culpa",
      name: "culpa",
      price: 1231.84,
      tmpProperty: undefined,
      activePromoId: 95,
    },
    {
      description: "voluptate mollit cillum esse",
      name: "ea",
      price: 1665.63,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "minim minim consequat ipsum",
      name: "esse",
      price: 515,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "qui aute irure sunt",
      name: "enim",
      price: 987,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "culpa dolore ea deserunt",
      name: "irure",
      price: 1553.76,
      tmpProperty: undefined,
      activePromoId: 76,
    },
    {
      description: "incididunt commodo est ea",
      name: "ea",
      price: 415.03,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "amet sunt consequat esse",
      name: "adipisicing",
      price: 1829.78,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "voluptate culpa voluptate laboris",
      name: "qui",
      price: 1666.4,
      tmpProperty: undefined,
      activePromoId: 1,
    },
    {
      description: "duis in aliquip cupidatat",
      name: "nisi",
      price: 995.09,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "reprehenderit voluptate quis qui",
      name: "voluptate",
      price: 1466.11,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "adipisicing elit aute veniam",
      name: "consectetur",
      price: 1538.4,
      tmpProperty: undefined,
      activePromoId: 65,
    },
    {
      description: "sit irure consequat voluptate",
      name: "nisi",
      price: 1186.16,
      tmpProperty: undefined,
      activePromoId: 8,
    },
    {
      description: "mollit dolore culpa pariatur",
      name: "exercitation",
      price: 1703.66,
      tmpProperty: undefined,
      activePromoId: 24,
    },
    {
      description: "ullamco exercitation in incididunt",
      name: "non",
      price: 800.17,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "dolor et sit occaecat",
      name: "ex",
      price: 882.43,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "dolore elit ut commodo",
      name: "eu",
      price: 810.3,
      tmpProperty: undefined,
      activePromoId: 53,
    },
    {
      description: "aliquip commodo officia nostrud",
      name: "eiusmod",
      price: 1446.68,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "esse occaecat proident non",
      name: "Lorem",
      price: 1166.92,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ad in deserunt esse",
      name: "minim",
      price: 1784.72,
      tmpProperty: undefined,
      activePromoId: 13,
    },
    {
      description: "ea esse cillum pariatur",
      name: "officia",
      price: 1968.6,
      tmpProperty: undefined,
      activePromoId: 81,
    },
    {
      description: "magna deserunt ea qui",
      name: "pariatur",
      price: 1645.17,
      tmpProperty: undefined,
      activePromoId: 40,
    },
    {
      description: "nostrud reprehenderit incididunt fugiat",
      name: "eu",
      price: 1860.47,
      tmpProperty: undefined,
      activePromoId: 12,
    },
    {
      description: "sit pariatur excepteur dolor",
      name: "ipsum",
      price: 351.78,
      tmpProperty: undefined,
      activePromoId: 44,
    },
    {
      description: "nulla ut labore irure",
      name: "et",
      price: 974.15,
      tmpProperty: undefined,
      activePromoId: 46,
    },
    {
      description: "incididunt labore occaecat proident",
      name: "eiusmod",
      price: 1824.6,
      tmpProperty: undefined,
      activePromoId: 44,
    },
    {
      description: "duis magna ut nisi",
      name: "voluptate",
      price: 949.83,
      tmpProperty: undefined,
      activePromoId: 52,
    },
    {
      description: "non Lorem est tempor",
      name: "et",
      price: 300.77,
      tmpProperty: undefined,
      activePromoId: 97,
    },
    {
      description: "anim ex magna sit",
      name: "ex",
      price: 249.99,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "cillum elit aliqua cillum",
      name: "mollit",
      price: 1856.35,
      tmpProperty: undefined,
      activePromoId: 56,
    },
    {
      description: "enim magna et nostrud",
      name: "non",
      price: 1435.65,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "enim aliquip quis velit",
      name: "proident",
      price: 1067.77,
      tmpProperty: undefined,
      activePromoId: 99,
    },
    {
      description: "laborum sunt minim commodo",
      name: "fugiat",
      price: 1581.76,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ex et irure nostrud",
      name: "pariatur",
      price: 1039.51,
      tmpProperty: undefined,
      activePromoId: 0,
    },
    {
      description: "sunt fugiat culpa laboris",
      name: "enim",
      price: 1315.97,
      tmpProperty: undefined,
      activePromoId: 25,
    },
    {
      description: "nisi amet veniam ipsum",
      name: "non",
      price: 752.7,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "consequat esse anim ipsum",
      name: "anim",
      price: 170,
      tmpProperty: undefined,
      activePromoId: 72,
    },
    {
      description: "velit cillum deserunt ex",
      name: "officia",
      price: 1310.95,
      tmpProperty: undefined,
      activePromoId: 67,
    },
    {
      description: "in ex aliquip excepteur",
      name: "ut",
      price: 636.19,
      tmpProperty: undefined,
      activePromoId: 100,
    },
    {
      description: "qui eu duis veniam",
      name: "proident",
      price: 1006.72,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "anim qui laboris do",
      name: "quis",
      price: 739.97,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "non esse velit ipsum",
      name: "deserunt",
      price: 606.01,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "Lorem in adipisicing excepteur",
      name: "quis",
      price: 1802.86,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "culpa sit fugiat incididunt",
      name: "Lorem",
      price: 1775.64,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "magna cupidatat dolor aliqua",
      name: "dolor",
      price: 593.96,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "officia cupidatat aute officia",
      name: "quis",
      price: 1342.73,
      tmpProperty: undefined,
      activePromoId: 73,
    },
  ],
};
